import { ArrowLeft, Zap } from "lucide-react";
import { useNavigate } from "react-router-dom";

export default function TermsPage() {
  const navigate = useNavigate();

  return (
    <div className="h-screen bg-background text-foreground transition-colors duration-200 overflow-y-auto">
      <div className="max-w-3xl mx-auto px-6 py-12">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-border pb-6 mb-8">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-indigo-600 flex items-center justify-center shadow-md shadow-indigo-500/20">
              <Zap size={16} className="text-white" />
            </div>
            <span className="text-md font-bold text-foreground tracking-tight">
              ResuPilot <span className="text-indigo-600">AI</span>
            </span>
          </div>
          <button
            onClick={() => navigate(-1)}
            className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
          >
            <ArrowLeft size={16} /> Back
          </button>
        </div>

        {/* Content */}
        <div className="prose prose-slate dark:prose-invert max-w-none space-y-6">
          <div>
            <h1 className="text-3xl font-extrabold text-foreground tracking-tight mb-2">
              Terms & Conditions
            </h1>
            <p className="text-sm text-muted-foreground">
              Last Updated: July 6, 2026
            </p>
          </div>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground">
              1. Acceptance of Terms
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              By creating an account or using the ResuPilot AI platform
              ("Service"), you agree to be bound by these Terms & Conditions. If
              you do not agree to these terms, do not access or use the Service.
              These terms apply to all visitors, users, and others who access or
              use the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground">
              2. User Accounts
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              To use most features of the Service, you must register for an
              account. You agree to provide accurate, current, and complete
              information during registration and to update such information.
              You are solely responsible for safeguarding your password and
              credentials. ResuPilot AI cannot and will not be liable for any
              loss or damage arising from your failure to protect your account.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground">
              3. Acceptable Use Policy
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              You agree not to use the Service to:
            </p>
            <ul className="list-disc pl-5 text-sm space-y-1.5 text-muted-foreground">
              <li>
                Upload or transmit any content that violates third-party
                intellectual property or privacy rights.
              </li>
              <li>
                Engage in any automated scraping, data mining, or harvesting of
                application content.
              </li>
              <li>
                Attempt to bypass or disable any security features, access
                controls, or rate limits.
              </li>
              <li>
                Use the Service for any unlawful, fraudulent, or malicious
                purposes.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground">
              4. AI-Generated Content Disclaimer
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              ResuPilot AI utilizes machine learning algorithms and language
              models to assist in drafting resumes, optimizing text, and
              simulating interviews. You acknowledge that AI-generated
              suggestions may occasionally contain errors, omission of facts, or
              inaccurate information. You are solely responsible for reviewing,
              correcting, and validating all output generated by the Service
              before using it in professional applications or employment
              submissions.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground">
              5. User Responsibilities & Content Ownership
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              You retain ownership of any raw data, resumes, or descriptions you
              upload to the Service. By uploading content, you grant ResuPilot
              AI a worldwide, non-exclusive, royalty-free license to store,
              process, and analyze your content solely to deliver and improve
              the Service. You represent and warrant that you own or have the
              necessary rights to use and authorize the processing of all
              uploaded content.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground">
              6. Intellectual Property Rights
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              The design, source code, visual layout, trademarks, logos, and
              proprietary templates of ResuPilot AI are the exclusive
              intellectual property of ResuPilot AI and its licensors. You may
              not copy, modify, distribute, or reverse engineer any part of the
              Service without explicit written permission.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground">
              7. Account Suspension & Termination
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              We reserve the right to suspend or terminate your account and
              access to the Service at our sole discretion, without prior
              notice, for conduct that we believe violates these Terms, harms
              other users, or infringes on our operations or intellectual
              property.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground">
              8. Limitation of Liability
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              To the maximum extent permitted by law, ResuPilot AI and its
              affiliates shall not be liable for any indirect, incidental,
              special, consequential, or punitive damages, or any loss of
              profits or revenues, whether incurred directly or indirectly,
              arising from your use of or inability to use the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-foreground">
              9. Contact Information
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              If you have any questions or feedback regarding these Terms,
              please contact us at:
              <br />
              <span className="font-semibold text-foreground">
                legal@resupilot.ai
              </span>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
