"""add_parsing_status_to_resume

Revision ID: 0be4ff9ec53c
Revises: fe514d17d385
Create Date: 2026-07-13 17:20:03.535317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be4ff9ec53c'
down_revision: Union[str, Sequence[str], None] = 'fe514d17d385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('parsing_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'parsing_status')
    # ### end Alembic commands ###
