"""remove interview answers and update interview models

Revision ID: 1d9d6257b4df
Revises: fc5b0191d6e9
Create Date: 2026-06-23 12:53:08.230211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9d6257b4df'
down_revision: Union[str, Sequence[str], None] = 'fc5b0191d6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('estimated_duration', sa.String(length=30), nullable=True))
    op.add_column('interview_questions', sa.Column('details_generated', sa.Boolean(), nullable=True))
    op.add_column('interview_sessions', sa.Column('candidate_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'candidate_type')
    op.drop_column('interview_questions', 'details_generated')
    op.drop_column('interview_questions', 'estimated_duration')
    # ### end Alembic commands ###
