"""expand profile table

Revision ID: 2a8bbb1b087f
Revises: 7b5b46ecd1ae
Create Date: 2026-06-18 17:28:17.131762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8bbb1b087f'
down_revision: Union[str, Sequence[str], None] = '7b5b46ecd1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('full_name', sa.String(length=150), nullable=True))
    op.add_column('profiles', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('location', sa.String(length=150), nullable=True))
    op.add_column('profiles', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('github_url', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('portfolio_url', sa.String(length=255), nullable=True))
    op.alter_column('profiles', 'headline',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'headline',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('profiles', 'portfolio_url')
    op.drop_column('profiles', 'github_url')
    op.drop_column('profiles', 'linkedin_url')
    op.drop_column('profiles', 'location')
    op.drop_column('profiles', 'phone')
    op.drop_column('profiles', 'full_name')
    # ### end Alembic commands ###
