"""create user jobs table

Revision ID: 309c578a899a
Revises: f5a6c73660e1
Create Date: 2026-06-25 14:24:46.428696

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "309c578a899a"
down_revision: Union[str, Sequence[str], None] = "f5a6c73660e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("job_title", sa.String(), nullable=False),
        sa.Column("company_logo", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("employment_type", sa.String(), nullable=True),
        sa.Column("apply_url", sa.Text(), nullable=True),
        sa.Column("posted_at", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("interview_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_jobs_job_id"), "user_jobs", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_user_jobs_user_id"), "user_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "interview_bookmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["interview_question_bank.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interview_bookmarks_id"), "interview_bookmarks", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interview_bookmarks_id"), table_name="interview_bookmarks")
    op.drop_table("interview_bookmarks")
    op.drop_index(op.f("ix_user_jobs_user_id"), table_name="user_jobs")
    op.drop_index(op.f("ix_user_jobs_job_id"), table_name="user_jobs")
    op.drop_table("user_jobs")
    # ### end Alembic commands ###
