"""add resume_json to resume

Revision ID: 50fec7e968ff
Revises: ab605fd92200
Create Date: 2026-07-08 17:25:00.430386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fec7e968ff'
down_revision: Union[str, Sequence[str], None] = 'ab605fd92200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('resume_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'resume_json')
    # ### end Alembic commands ###
