"""create user roadmap table

Revision ID: 7a00de410ec4
Revises: cd8a18eb1fdf
Create Date: 2026-07-08 16:11:49.940565

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '7a00de410ec4'
down_revision: Union[str, Sequence[str], None] = 'cd8a18eb1fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
