"""normalize profile tables

Revision ID: 7b5b46ecd1ae
Revises: 13a3146e7426
Create Date: 2026-06-16 14:45:42.223297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5b46ecd1ae'
down_revision: Union[str, Sequence[str], None] = '13a3146e7426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=False),
    sa.Column('start_year', sa.String(length=20), nullable=True),
    sa.Column('end_year', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tech_stack', sa.Text(), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('live_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('profiles', 'skills')
    op.drop_column('profiles', 'education')
    op.drop_column('profiles', 'projects')
    op.drop_column('profiles', 'experience')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('experience', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('projects', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('education', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('user_skills')
    op.drop_table('user_projects')
    op.drop_table('user_experience')
    op.drop_table('user_education')
    # ### end Alembic commands ###
