"""remove status column

Revision ID: 89ecaaa10dd2
Revises: 54179255e3cd
Create Date: 2026-06-23 18:30:05.263138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ecaaa10dd2'
down_revision: Union[str, Sequence[str], None] = '54179255e3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_question_bank', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_question_bank', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
