"""update experience dates

Revision ID: 993a967ba7f3
Revises: 2a8bbb1b087f
Create Date: 2026-06-20 21:52:35.316556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993a967ba7f3'
down_revision: Union[str, Sequence[str], None] = '2a8bbb1b087f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_experience', sa.Column('start_month', sa.String(length=20), nullable=True))
    op.add_column('user_experience', sa.Column('start_year', sa.Integer(), nullable=True))
    op.add_column('user_experience', sa.Column('end_month', sa.String(length=20), nullable=True))
    op.add_column('user_experience', sa.Column('end_year', sa.Integer(), nullable=True))
    op.add_column('user_experience', sa.Column('currently_working', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_experience', 'currently_working')
    op.drop_column('user_experience', 'end_year')
    op.drop_column('user_experience', 'end_month')
    op.drop_column('user_experience', 'start_year')
    op.drop_column('user_experience', 'start_month')
    # ### end Alembic commands ###
