"""add tech_skill to interview questions

Revision ID: 9eda89821769
Revises: 1d9d6257b4df
Create Date: 2026-06-23 15:27:57.716075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eda89821769'
down_revision: Union[str, Sequence[str], None] = '1d9d6257b4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('tech_skill', sa.String(length=100), nullable=True))
    op.drop_column('interview_questions', 'key_points')
    op.drop_column('interview_questions', 'tip')
    op.drop_column('interview_questions', 'common_mistakes')
    op.drop_column('interview_questions', 'follow_up_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_questions', sa.Column('follow_up_questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interview_questions', sa.Column('common_mistakes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interview_questions', sa.Column('tip', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interview_questions', sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('interview_questions', 'tech_skill')
    # ### end Alembic commands ###
