"""add difficulty to interview question bank

Revision ID: d0cc9e38bc5f
Revises: 0be4ff9ec53c
Create Date: 2026-07-14 10:43:07.102995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0cc9e38bc5f"
down_revision: Union[str, Sequence[str], None] = "0be4ff9ec53c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column(
        "interview_question_bank",
        sa.Column("difficulty", sa.String(length=20), nullable=True),
    )
    # Update existing rows to have default 'Medium'
    op.execute("UPDATE interview_question_bank SET difficulty = 'Medium'")
    # Alter column to be NOT NULL
    op.alter_column("interview_question_bank", "difficulty", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interview_question_bank", "difficulty")
    # ### end Alembic commands ###
