"""add job cache tables

Revision ID: eca40e1ba14e
Revises: 4c56955f6026
Create Date: 2026-06-25 16:39:18.397434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eca40e1ba14e'
down_revision: Union[str, Sequence[str], None] = '4c56955f6026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_cache_job_id'), 'job_cache', ['job_id'], unique=True)
    op.create_table('search_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('jobs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_cache_query'), 'search_cache', ['query'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_cache_query'), table_name='search_cache')
    op.drop_table('search_cache')
    op.drop_index(op.f('ix_job_cache_job_id'), table_name='job_cache')
    op.drop_table('job_cache')
    # ### end Alembic commands ###
