import {
  FileText,
  BarChart3,
  MessageSquare,
  Search,
  Briefcase,
  Brain,
} from "lucide-react";

export const features = [
  {
    icon: FileText,
    color: "#4F46E5",
    bg: "#EEF2FF",
    title: "AI Resume Builder",
    desc: "Generate ATS-friendly resumes in minutes.",
    path: "/resumes",
    featureType: "resume-builder",
  },
  {
    icon: BarChart3,
    color: "#14B8A6",
    bg: "#F0FDFA",
    title: "Resume ATS Analysis",
    desc: "Analyze resumes against job descriptions.",
    path: "/analysis",
    featureType: "ats-analysis",
  },
  {
    icon: MessageSquare,
    color: "#4F46E5",
    bg: "#F5F3FF",
    title: "Interview Preparation",
    desc: "Practice Technical, HR and Behavioral interviews.",
    path: "/interview",
    featureType: "interview-prep",
  },
  {
    icon: Search,
    color: "#14B8A6",
    bg: "#FFFBEB",
    title: "Job Discovery",
    desc: "Discover opportunities matched to your skills.",
    path: "/tracker",
    featureType: "job-discovery",
  },
  {
    icon: Briefcase,
    color: "#4F46E5",
    bg: "#F0FDF4",
    title: "Application Tracker",
    desc: "Track every application from Applied to Offer.",
    path: "/tracker",
    featureType: "application-tracker",
  },
  {
    icon: Brain,
    color: "#14B8A6",
    bg: "#FEF2F2",
    title: "AI Career Assistant",
    desc: "Receive personalized career recommendations.",
    path: "/dashboard",
    featureType: "ai-assistant",
  },
];
